### ISSUE TITLE
Results cake plots

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#130]
The cake plots might be a bit confusing to users. 
The following scenario is from the Ontario pilot, with min set.

First cake plot:

![image](https://user-images.githubusercontent.com/3445092/129039299-9e0544ce-1829-479e-b70f-ccacc3f64fc1.png)

Second cake plot:

![image](https://user-images.githubusercontent.com/3445092/129039353-54147536-9682-4eee-b56a-b5bc050aa2a0.png)

You can see that both have a goal of 20% and a solution of 20%. In the first one the goal (blue) trumps the solution (red) in the second one this is reversed. This behavior is confusing to users I think.

What do you think?

I think this is maybe even more confusing when using a budget.

Not sure how this could be improved. I was thinking transparency, but that would create weird colors. 

Also, the legend for the results/themes section shows "Includes" instead of "current".

**Comment by jeffreyhanson** [comment]
Thanks for catching this. I can try tweaking the plots it to give a consistent appearance in such cases. 

Regarding the legends, yeah, I put "Includes" there because I thought "current" might be confusing -- because if you generate a solution and change which includes are selected, then the includes settings previously used to generate the solution aren't "current" anymore. Shall I change the text in the popup text to display "included" instead of "current"?

**Comment by ricschuster** [comment]
Thanks Jeff!

Using "Included" sounds good to me, thanks!

**Comment by jeffreyhanson** [comment]
I think I've fixed this issue and pushed an updated version online (i.e. ncc.carleton.ca), could you please take a look and double check that it's fixed? Under this new version, the pie slices will have a small amount of padding to break ties (e.g. if current == goal,  then goal will have a small padding so that it sticks out past the current). What do you think?

**Comment by ricschuster** [comment]
This is perfect! Thanks very much!
