### ISSUE TITLE
0% area error message

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#140]
0% area budget seems to allow optimisation but generates an error message. This is fine of course, but could either have a warning, or just discuss this in the manual? Perhpas the latter is easier.

**Comment by jeffreyhanson** [comment]
Thanks for catching this. Yeah, I could update the app to (1) throw a specific error message saying that 0% budgets are not acceptable, or (2) update the slide bar for the area budget so that the smallest value is 1% (so it's not possible to do a 0% budget with budget turned on). I think (2) might provide a better user experience - what do you think?
