### ISSUE TITLE
total area budget and includes

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/wheretowork#141]
I'm pretty sure this isn't a technical issue - just something I don't understand. If I put total area budget to 100% and select all the includes, the solution seems to get to 79% of area. If I unselect the includes, it gets up to 100% (which is what I'd have expected for both runs). It's almost certainly something I'm missing, but figured I should mention just in case.

**Comment by jeffreyhanson** [comment]
Yeah - that's strange. I would have expected 100% of the area to be selected in both cases. Do you remember what the targets were? I wonder if they were low enough such that they could all be met with < 100% of the study area selected (and so selecting 100% and 79% of the study area is optimal)?

**Comment by jeffreyhanson** [comment]
Yeah, I just looked into it and my earlier suspicious were correct. Assuming you're using the default goals, then you don't actually need to select 100% of the study area in order to meet them. As such, the optimization process won't neccesarily select 100% of the study area even if you  set a maximum area of budget of 100%. To verify this, if we (1) generate a solution with default settings and an area budget of 100%, we can see that the solutions meets all the goals even though <100% of the study area is selected; and (2) generate a solution with default setting, area budget of 100%, and set the goal for the first themes to 100%, we can see the solution covers nearly 100% of the study area (because the first themes covers like 98% of the study area) -- meaning that the extent of the solution is being driven by the goals.
