### ISSUE TITLE
Differentiate National and Regional datasets

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#149]
Suggestion from Cindy McCallum (BC GIS): I think it might be nice to be able to differentiate between the National and Regional datasets – maybe some kind of flag on the National ones?

**Comment by jeffreyhanson** [comment]
Yeah, I like the idea of providing more information on each dataset within the application. We could add a specific field to differentiate between National vs. Regional datasets to display different icons for them, but I wonder if maybe a more general descrtion text would be more helpful? We have it so that when the user mouses-over the name of a theme/weight/include the app shows the description text as a tooltip? This information could also indicate if the data are National or Regional. What do you think? Or is there a clear need to specifically differentiate between National vs. Regional?

**Comment by ricschuster** [comment]
A general description text sounds good too. Would be a neat feature, especially if projects are shared with external partners.

The ability to specifically differentiate between National and Regional data would be good though, because National data is under the control of the National team. These are data that will have to be included in an analysis. Regional data are under the control of each region and are optional, although the assumption is that Regions will pretty much always include regional data.

**Comment by jeffreyhanson** [comment]
Ok sounds good! Ok, based on that, it seems to me that there is a need to differentiate between "optional" vs. "important" datasets (as opposed to National or Regional specifically). Is that generalization correct? If so, we could include a field for each theme/weight/include that specifies if something is "critical" or not (i.e. a boolean field), and if something is critical, then we could add an icon for those datasets to table of contents sidebar and the solution settings sidebar (e.g. like a red exclamation mark) in the app?

**Comment by ricschuster** [comment]
NCC specific we have 'national' and 'regional'. That's the way we have talked about themes from the beginning and what makes most sense to people. Not sure about the best way to visualize that in the app. Given that these two states are NCC specific, I wonder whether this could be generalized as well. I imagine for the public facing version, we could have a category of 'built in' and 'user supplied'. Not super important to make that distinction I think, but if we have the 'national' and 'regional' groups already, it might be simple enough, or maybe not?

Yes, the project config files should specify this.
