### ISSUE TITLE
DockerHub pull

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#153]
Does a DockerHub pull make any changes to the /opt/wheretowork/projects directory?
I'm sure I added the `quebec_pilot` folder to the projects folder on Friday, but this morning it was gone.
I've added it again now, but am curious what might have happened?

**Comment by jeffreyhanson** [comment]
Nah - this is totally my fault for manually updating the server and not paying enough attention to what I was doing. Since we updated the app to include weight/include/theme checks to prevent `.`'s in the names, I needed to update the pilot case study dataset because a couple of the layers had `.`'s in their names. So, I did this by sshing into the server, deleting the `/opt/wheretowork/projects` directory and copying across all the built-in projects back into the `/opt/wheretowork/projects`. I'm sorry, I completely forgot that you had added another dataset. I should have just copied the pilot project specifically instead of nuking the whole directory. 

It just occured to me that I might not be the only person to ever accidently delete some project data. Since the project data will eventually be stored in a shared directory - that a bunch of different people can access - are there any plans to backup the projects?

**Comment by ricschuster** [comment]
Good to know that my mind is still somewhat working and that this can be explained. No worries at all about nuking the directory, was an easy fix.

IT does backups. Not sure what the usual procedures are for shared directories, but excellent point, we need to eventually figure that out.

**Comment by jeffreyhanson** [comment]
Ok - glad to hear it was an easy fix. 

Hmm, perhaps in the short term, we could put all the project data in a GitHub repo? It seems like the data isn't too large for it to be problem on GitHub yet.

I think I've answered your question on this, so I'll close this issue now - but please feel free to re-open if anything's not clear.
