### ISSUE TITLE
Alternative boundary data format

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/wheretowork#160]
@JCLaurence and I had a meeting today about the project data format for the WTW tool. In this meeting, we talked about how the data format for the boundary data is fairly complex. IIRC, it would make things easier on JC's end if the WTW tool could import boundary data using an alternative data format (i.e. using the exact same index/id values specified in the attribute table data). So, I'll look into adding this functionality into the WTW tool. The idea is that users could upload the boundary data as a ".csv" or ".csv.gz" format (current supported format), or as a ".dat" or ".dat.gz" format (alternative format), and both formats would be acceptable.

@JCLaurence, please feel free to add in any missing details, or correct me if I've got something wrong?

@ricschuster, how does that sound? I'm planning on (hoping to) adding this functionality today, so it doesn't block progress for @JCLaurence 

EDIT: new format is refered to as an alternative format per discussion below.

**Comment by jeffreyhanson** [comment]
@JCLaurence, to clarify, under the Marxan format, should the boundary data file be a comma-delimeted file (to follow conventions with the attribute table data format), or should it be a tab-delimeted file (to follow exactly same conventions as the Marxan format)? I'm happy with either option - what do you think is best?

**Comment by JCLaurence** [comment]
Comma-delimited for sure!! Tabs drive me nuts

Sent from my iPhone

On Sep 8, 2021, at 7:04 PM, Jeff Hanson ***@***.***> wrote:

﻿
ATTENTION:External Email|Courriel Externe
________________________________

@JCLaurence<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJCLaurence&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7C76806ed0ee0141049c5408d9731cf0f9%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667390403420719%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RIzVE7XW2XTcd27lJ%2BbBlvLrT5n6NT5n6UKtwQJ33qY%3D&reserved=0>, to clarify, under the Marxan format, should the boundary data file be a comma-delimeted file (to follow conventions with the attribute table data format), or should it be a tab-delimeted file (to follow exactly same conventions as the Marxan format)? I'm happy with either option - what do you think is best?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCC-CNC%2Fwheretowork%2Fissues%2F160%23issuecomment-915629696&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7C76806ed0ee0141049c5408d9731cf0f9%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667390403430679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4K%2B2%2FvSrq2k20uz3MjEMvoSQznmeFt9t%2F2P2xvjkaGM%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPS6W7PVKDIMLQP6P2CV4KTUA7TV5ANCNFSM5DVU72RA&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7C76806ed0ee0141049c5408d9731cf0f9%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667390403440639%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sK0Qfy4EhU8LMMWWgV1SI1wExEW2BE44h6EKc3mthVU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7C76806ed0ee0141049c5408d9731cf0f9%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667390403440639%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S%2FT44Fm4%2BphhsPqha6kmXhH5lgYMRWEvNdsQe3ZNUvg%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7C76806ed0ee0141049c5408d9731cf0f9%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667390403450602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b5UJtXyb1g8fypSfrg6234NJcg5CANzo%2B3ouhXrDwzU%3D&reserved=0>.

**Comment by jeffreyhanson** [comment]
Ok sounds good! Given that, maybe we shouldn't refer to this as a "Marxan" data format and instead an "alternative file format"?

**Comment by JCLaurence** [comment]
I also agree with that!

Sent from my iPhone

On Sep 8, 2021, at 7:21 PM, Jeff Hanson ***@***.***> wrote:

﻿
ATTENTION:External Email|Courriel Externe
________________________________

Ok sounds good! Given that, maybe we shouldn't refer to this as a "Marxan" data format and instead an "alternative file format"?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCC-CNC%2Fwheretowork%2Fissues%2F160%23issuecomment-915637213&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Ce9e263bca57b41aaa07908d9731f55af%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667400682376829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9cc0R9FfTCVXvpVThhrZvOkfdHB5pOWMR5qvuLK%2B%2FEA%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPS6W7MCKHDYHT5K3OCW4B3UA7VWFANCNFSM5DVU72RA&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Ce9e263bca57b41aaa07908d9731f55af%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667400682376829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WKaFJdJQbfBGmwdfOLU9XvBtVouyRynj9wktYRyCOKQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Ce9e263bca57b41aaa07908d9731f55af%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667400682376829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uwx3YxYlTWarRCGfhD226IQiUJ3%2FVnfcgPnYj7057eU%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjc.laurence%40natureconservancy.ca%7Ce9e263bca57b41aaa07908d9731f55af%7C28c6c543842241cf8beaa257eddcd88c%7C0%7C0%7C637667400682386776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9fbpjKfnqdX3fYZt1KulixAZ9LwroM7Hq62nAxCaVy4%3D&reserved=0>.

**Comment by jeffreyhanson** [comment]
Ok - I've implemented the alternative boundary data format. Under this format, the file extension should be `.dat` or `.dat.gz`, and have the following columns `id1`, `id2`, and `boundary`. I have also updated the examples projects `sim_vector2` and `sim_raster2` to use this alternative boundary data format (see [here](https://github.com/NCC-CNC/wheretowork/tree/master/inst/extdata/projects)).

**Comment by JCLaurence** [comment]
That's perfect, I appreciate it!
JC

________________________________
