### ISSUE TITLE
Saving problem/solution parameters

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#180]
From Trevor in BC: "We wondered if the capability to save a solutions parameters could be included?  For example, if we wanted to go back in at a later date and change 1 or 2 of the parameters set, we could open up the tool where we left off."

**Comment by jeffreyhanson** [comment]
Yeah, that's a great idea! I think that functionality would be really useful. It would probably be a fair amount of work, much less than upgrading the mapping functionality though. We'd have to come up with a file format for storing the parameters used to generate solutions. For instance, we could update the project YAML file to contain a section for storing solution metadata (e.g. name of column in attribute data and colors for plotting). Since the existing data structures/classes/widget interfaces would work for this, the main updates would involve adding code to ingest solution parameters when the project data are uploaded.

**Comment by ricschuster** [comment]
Great to hear! Maybe we can revisit this once the 'release' version of "What to do" is finalized?

**Comment by jeffreyhanson** [comment]
Yeah - sounds good!

**Comment by jeffreyhanson** [comment]
Just recording this here for future reference, IIRC Veronique asked about this functionality too.

**Comment by DanWismer** [comment]
@ricschuster 
Wondering if PR #285 mostly handles this? A user can upload a .yaml that stores a previous runs toggles and slider values to update the solution settings. Then from there, the user can re-run the optimization. There is no storing of the output, but the output can easily be reproduced.

**Comment by DanWismer** [comment]
PR #285
