### ISSUE TITLE
Loading in large shapefile (PEI): `rcpp_str_tree_to_sparse_matrix: std::bad_alloc` error

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#230]
I will have to investigate this, but I am thinking it has to do with when the attribute table gets translated to a sparse matrix and it is hitting some type of memory limit...?

**Comment by DanWismer** [comment]
Following up with my chats with @jeffreyhanson  and @ricschuster, the error is occurring when the boundary matrix is being generated for very large planning units (`new_dataset_from_auto` `# prepare boundary data`). A solution to this is to try defining the `str_tree` parameter as `FALSE` or skip the boundary matrix all together. If the boundary matrix is skipped, the `Spatial clustering` setting will need to be disabled on the UI.

**Comment by ricschuster** [comment]
Thanks Dan! What do you think about a check box to allow users to skip the boundary matrix on the 'upload shapefile' screen?

**Comment by DanWismer** [comment]
I am wondering if I can use the same checkbox for turning off mapping? The logic is that if you are already turning of mapping because it is a large project, then you may as well skip the boundary calculation. 

Alternatively, I could wrap it in a `try` statement, and if the boundary fails to build, then continue on. However, that may just be unnessaary processing if you know the project is large...

**Comment by ricschuster** [comment]
I like the idea of including this with turning off mapping. For raster datasets this would also make sense, because if the problem is big enough for a user to want to turn off mapping, its probably also too big to reasonably include the spatial clumping.

**Comment by DanWismer** [comment]
@jeffreyhanson 

I was able to get the `min_set_result` to return a `Result` object using a `boundary_data` of `NA`. The next block of code in the `server_generate_new_solution.R` I was getting hung up on is when it hits `new_solution_from_results`. The `Solution` class uses the `reserve_sizes` function from `utils_spatial_misc.R` to calculate statistics results. 

The `reserve_sizes` functions uses a `boundary_matrix` to calculate the size of individual reserves in a solution. However with no boundary matrix, I just went with returning the value of 0:
![image](https://user-images.githubusercontent.com/29556279/189756687-575f8bca-b7a8-4635-9dbd-96cdbe7ae6a2.png)

This allows for the `new_statistics` to calculate without an error:
![image](https://user-images.githubusercontent.com/29556279/189756944-e0b444d2-3448-4f0e-870a-4e20b97aba92.png)

However, this returns the summary table to this:
![image](https://user-images.githubusercontent.com/29556279/189757159-d665d2d1-d6b0-42a9-8f49-619e56ab6cd3.png)

I am wondering, would there be a way to calculating reserve size without using a boundary matrix? This would really only need to be for spatial uploads (shapefile)

**Comment by jeffreyhanson** [comment]
To my knowledge, it's not possible to calculate reserve sizes without the boundary matrix. Note that I define a "reserve" as a set of planning units (e.g grid cells) that are selected in a prioritization and form a spatially contiguous mass (e.g., they clump togeather into an island). This is because -- in order to split the prioritization into a set of reserves -- we need to know which planning units are next to each other, and this information is encoded in the boundary matrix. So, without the boundary matrix, we can't split up a prioritization into a set of reserves and, in turn, calculate reserve sizes. Does that help?

**Comment by DanWismer** [comment]
Thanks for that - to confirm, no boundary matrix means no reserve size calculation? Does returning a value of 0 make the most sense for the `reserve_size` function if `boundary_matrix` is `NA` ? I suppose I would need to somehow change the Summary table to show NA instead of 0 for those values to make it a little more clear for the user.

**Comment by jeffreyhanson** [comment]
Hmm, I just realized: if this was super important, you could use `adjancency_matrix()` to create an adjacency matrix (which is computationally less demanding than a boundary matrix), which would encode information on which planning units are next to each other (but wouldn't have boundary information needed for boudnary penalties). But you would then want to update the "project file format" to contain an additional file that contains this information, and that could take a while?

**Comment by jeffreyhanson** [comment]
Yeah, I think returning `NA` makes the most sense. Yeah, to help improve user experience, I wonder if the JS code could be tweaked such that if the value is a missing number (`NA` value) it shows the text "Unknown" or "Not calculated" or something?

**Comment by ricschuster** [comment]
> Yeah, I think returning `NA` makes the most sense. Yeah, to help improve user experience, I wonder if the JS code could be tweaked such that if the value is a missing number (`NA` value) it shows the text "Unknown" or "Not calculated" or something?

Agreed.

**Comment by DanWismer** [comment]
The only scenario I can think of that we are wanting to skip calculating a boundary matrix is for spatial imports (shapefile) where the user has a ton of planning units. I think asking the user to submit an additional adjacency matrix would trip them up. I assume generating that adjacency matrix on the fly would be time consuming as well. I think for now I will go with that NA approach you mention and revisit calculating an adjacency matrix on the fly later.

Since the project is a shapefile, do we need an adjacency matrix? Could we calculate total reserves by dissolving planning units that touch, then count them up?

**Comment by jeffreyhanson** [comment]
Yeah sounds good! 

Yeah, the adjancy matrix function provides data on the spatial arrangement of planning units to work out which planning units form reserves. Although you're right -- that approach would definitely work -- I don't think it wouldn't be as performant as using the adjacency matrix and reserve size functions implemented in the tool. This is because if you're dissolving planning units togeather than you're spending time trying to work out (a) what planning units are next to each other, (b) what the spatial boundary of each reserve looks like, so (c) you can calculate reserve sizes. However, we actually only need (a) and information on the total size of each planning unit (which is computationaly easy to compute, e..g, using `st_area()`). Using (a), we can express our selected planning units as a graph (not a plot, but a mathematical network using graph theory, see [here](https://github.com/NCC-CNC/wheretowork/blob/49ddf1a5ae608304c6eebe34baaff1a3778ffa19/R/utils_spatial_misc.R#L113)) and then use algorithms (that are way smarter then me, see https://igraph.org/r/doc/components.html) to very quickly work out which planning units are form connected components (in other words, reserves) (see [here](https://github.com/NCC-CNC/wheretowork/blob/49ddf1a5ae608304c6eebe34baaff1a3778ffa19/R/utils_spatial_misc.R#L116)). This means we can identify which planning units are in which reserves, and then we can claulcate total reserve sizes by simplying summing togeather the areas for planning units within each reserve (see [here](https://github.com/NCC-CNC/wheretowork/blob/49ddf1a5ae608304c6eebe34baaff1a3778ffa19/R/utils_spatial_misc.R#L118-L121)). How does that sound? 

Also, the `adjacency_matrix()` function has optimizations for both sf and raster data. E.g., if we have a raster, then we don't even to do geoprocessing as we can identify which planning untis are next to each other based on cells indices/row numbers/column numbers (see https://github.com/prioritizr/prioritizr/blob/master/R/adjacency_matrix.R).

**Comment by DanWismer** [comment]
Thanks for that explanation @jeffreyhanson. That's pretty cool that you can figure out connected planning units all from area. I will give the `adjacency_matrix` a shot in a different PR. For now I will stick with the low-tech "Not calculated" approach and circle back to this later.

Having no boundary data, I am disabling the `Spatial clustering` setting. Do I also need to disable the `Total area budget` ?

**Comment by jeffreyhanson** [comment]
No worries! Yeah - sounds good! Yeah, disabling the spatial clsutering setting sounds like a good idea. Nah, the the total area budget can remain I think (since the code just needs the total area of each planning unit - which is computed using the GIS planning unit data, e.g. shapefile - and not the boundary data).

**Comment by DanWismer** [comment]
Get this error when app is ran inside a docker container:
`Warning: Error in methods::as: no method or default for coercing “matrix” to “dgCMatrix”`
