### ISSUE TITLE
No stop button in dev mode

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#234]
@jeffreyhanson 

I just recently noticed that when I run Where To Work locally (`run_dev.r`) I don't ever see the stop button when I hit optimize. I understand this is where the async kicks in. Is that something that only goes when in a docker container and then the stop button shows?

**Comment by jeffreyhanson** [comment]
Hmm, I have a vague recollection that the asynch stuff might not work on Windows properly (because it relies on FORK clusters?), so I might have been clever enough to hide the stop button on Windows systems. Or I might be making this up? Not sure. I'd recommend looking through the code sorry. If it's not easy to figure out, we can look at this during the next meeting?

**Comment by DanWismer** [comment]
Bingo, that's exactly what you did! In the `server_initialize_app.R` you hide the stop button if the `strategy` variable is not identical to `multicore`. In `app_globale.R` is where the `strategy` variable is defined:

```   # initialize asynchronous processing
  ## identify strategy
  strategy <- wheretowork::get_golem_config("strategy")
  if (identical(strategy, "auto")) {
    if (identical(Sys.getenv("R_CONFIG_ACTIVE"), "shinyapps")) {
      strategy <- "multicore"
    } else if (identical(.Platform$OS.type, "unix")) {
      strategy <- "multicore"
    } else {
      strategy <- "multisession"
    }
  }
```
I am on windows so I think the strategy variable gets set to `multisession` ?

**Comment by jeffreyhanson** [comment]
Ah - awesome! Yeah, if the golem parameters specify that the strategy variable should be automatically determined, then the strategy variable gets set to `"multisession"` on Windows.
