### ISSUE TITLE
Tool weights vs `add_feature_weights` in prioritizr

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/wheretowork#236]
This question is mostly for @jeffreyhanson I think:

Using the `Total area budget` in Where To Work do you think the `Weights` would/could preform in a similar way to the `add_feature_weights` function in prioritizr if the layers in `Weights` would mirror the `Themes` layers?

Not sure if you have ever tested this, but I was wondering what your thoughts were on this?

(Its mostly for documentation and no need to be a perfect match between the two)

**Comment by jeffreyhanson** [comment]
Technically, when using a total area budget, the Weights are added as features with targets set according to the weight factor (see  https://github.com/NCC-CNC/wheretowork/blob/master/R/fct_min_shortfall_result.R#L228-L273) - so I don't think so. If you had the same layer as a Weight and as a Feature/Theme, then this would be like including the same feature twice in the optimization problem with two different targets.

**Comment by ricschuster** [comment]
Thanks Jeff! Makes sense. 
Is there a way in the current `Where To Work` tool setup you can think of that could somewhat emulate the `add_feature_weights` functionality?
Aside from adding that feature to `Where To Work` the way I described above seemed the closest I could think of.

**Comment by jeffreyhanson** [comment]
Yeah, it's not really possible with the current set up. I beleive the reason why we might have previously scrapped this idea is because we would need to (1) update the app to store information on feature weights, (2) update the data format to store information on weights, (3) come up with some terminology to distinguish between the Weights currently implemented in the app and relative importance measures for the features (i.e., weights per prioritizr terminology), and (4) update the UI to allow users to specify features weights when the total budget parameter is toggled on (and also make this intuitive so that users know that weights have no effect when the parameter is toggled off)

**Comment by ricschuster** [comment]
Thanks Jeff!
Yes to all four points you mentioned. Seemed and seems like a reasonable trade-off here. Adding weights would complicate things considerably.
