### ISSUE TITLE
excludes 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#255]

**Comment by DanWismer** [comment]
@jeffreyhanson 

What are your thoughts on how to handle when an exclude overlaps an include? My gut is saying the include should win in those cases. Also, some type of message should be prompted to the user indicating that there is overlap between the exclude and the include layer. I am just thinking where the best place is to put that message.... maybe as a new row in the summary output?

![image](https://user-images.githubusercontent.com/29556279/199515463-7ac2a64b-beb0-436b-88e3-c6fd0029c48f.png)


Here is an example of an include (existing park, green) that overlaps an exclude (major highway, orange):
  
![image](https://user-images.githubusercontent.com/29556279/199514270-849651de-5531-4378-a8bf-8930e0cb1977.png)

**Comment by DanWismer** [comment]
Another questions here....
I have hade some runs show results not having 100% includes: 
![image](https://user-images.githubusercontent.com/29556279/199528569-d34715c1-3780-4099-8336-b822f511712f.png)

Any idea why the output wouldn't consider all the included areas in the solution? I get this when I increase some of the theme goals and also have the excludes on.

**Comment by DanWismer** [comment]
Another question...

Does anyone have experience with this error: `Error: argument to initial solution does not obey col_ub`

I get it on the `test_min_set_result` , spatial clustering

**Comment by jeffreyhanson** [comment]
Hi,

With regards to your questions:

> What are your thoughts on how to handle when an exclude overlaps an include? My gut is saying the include should win in those cases. Also, some type of message should be prompted to the user indicating that there is overlap between the exclude and the include layer. I am just thinking where the best place is to put that message.... maybe as a new row in the summary output?

Yeah, I agree with including the include and not excluding the exclude. Rather than having this message in the output, what do you think about having it come up when the user toggles on the include/exclude? E.g., if the app has an include toggled on, and they toggle on an overlapping exclude, a popup could appear that tells the user about this issue and says that overlaapping areas will be included? This would also provide a bit more context because when there are multiple includes/excludes then the user can determine which combinations of includes/excludes are overlapping? 

> Any idea why the output wouldn't consider all the included areas in the solution?

Not sure, have you manually updated the min shortfall and min set functions to handle cases when a planning unit is locked in and locked out? Specifically, add new code to ensure that any planning units with TRUE's for both locked in and locked out are FALSE for the locked out? If not, I'd do that first and see if that resolves the issue.

> Does anyone have experience with this error: `Error: argument to initial solution does not obey col_ub`?

Nah, I haven't seen that before. Perhaps there's an issue with the caching of the preliminary solution? Maybe this is related to the previous issue - not sure sorry.

**Comment by DanWismer** [comment]
Thanks @jeffreyhanson for those comments. 

I like that idea of having the pop-up show on toggle in the new solution side bar indicating if an exclude overlaps an include. I can give that a go. I force all excludes to have a status of `FALSE` (toggled off) on init and will only show the overlap message with excludes toggled (instead of showing the overlap message for both includes toggled and excludes toggled)

**Comment by jeffreyhanson** [comment]
Sounds good! Even though the excludes start as toggled off, it might be worth thinking about having the popup display when an include is toggled on, because (1) at the start, the exclude is toggled off and the include is toggled on, (2) the user could toggle off the include, (3) the user could toggle on the exclude, and then (4) the user could toggle the include back on. Thus the user could toggle on both an overlapping include and exclude, without the "toggle on to trigger an overlap" being to toggle on the exclude. Does that make sense? I might be missing something though.

**Comment by DanWismer** [comment]
I figured out how to track the includes and excludes that overlap. Now I am working on how to best display that to the user. Currently I have it as a pop-up when the user toggles on an exclude or include:
![image](https://user-images.githubusercontent.com/29556279/200356055-4199f653-81df-452c-b114-edce04da9d9d.png)

However, I am now thinking that it would be better (less complicated code as well) to just have a new warning icon with a tool tip on the layers that overlap:
![image](https://user-images.githubusercontent.com/29556279/200356876-6c7de4bf-a7b5-4bed-82bd-fa783396a620.png)
This way the info is always there for the user no matter if the include or exclude is toggled.

**Comment by DanWismer** [comment]
I think this is cleaner:
![image](https://user-images.githubusercontent.com/29556279/200387028-8fb75bf2-231a-48c4-ba8f-57b4b494ea0a.png)

![image](https://user-images.githubusercontent.com/29556279/200387181-2e5caa1b-ca22-489c-9e0c-695ca5bf6657.png)

**Comment by jeffreyhanson** [comment]
Yeah - that's genius - awesome work!!

**Comment by ricschuster** [comment]
Agreed. This is awesome Dan!

**Comment by DanWismer** [comment]
I have a  scenario where the user may want the `exclude` to win over the `include` in a solution.

For example, we have a WtW Prairie Grassland project that spans over AB, SK and MB. Data has been prepped to cover those three regions, however we have a scenario where we want to limit the solution to only a single region. 

Currently, you would need to got back and prep data so that there are three sperate projects (Prairie_Grassland_AB, Prairie_Grassland_SK, Prairie_Grassland_MB). However, with the new `excludes` feature, we can mask out areas we do not want in the solution. But if includes always wins, we will get the includes show up from other regions in the solution. 

I am now thinking we need another button to force `includes` or force `excludes` to win when there is overlap. I need to figure out where the best place for that would be ....

**Comment by DanWismer** [comment]
@jeffreyhanson 

I have a suspicion that something is up with how intermediate data is cached in `min_set_result` and `min_shortfall_result` and how the exclude / include overlap works.

For example, when I spin up the app and have includes wins, includes win the overlap. Then when run a second time, only changing the overlap setting for excludes to win, includes still win. However, if I change the theme goals and run with excludes win, then excludes win.

It seems that if nothing is changed on a second run, then the cache output autocratically outputs the first run.

**Comment by DanWismer** [comment]
... ok I think all I needed to do was pass the `overlap` flag to the cache keys:
![image](https://user-images.githubusercontent.com/29556279/202533215-7cc44139-61df-43cc-bd61-1fcd0cc0dcaf.png)

**Comment by jeffreyhanson** [comment]
Yeah, that sounds like that would fix it
