### ISSUE TITLE
grouped themes can not have different units

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#262]
@jeffreyhanson 

I noticed I can not create grouped themes with different units. For example, we have a Land Cover theme with wetland, forest, grassland, lakes, rivers and shoreline. River and shoreline are lengths (km) and everything else is area (km2). Ideally it would be nice to group all of those layers under the one theme - Land cover.

What your thoughts are on this? Would a grouped theme with features having different units not work because of the goal setting? Or do you think mixing features with different units is feasible within a grouped theme?

**Comment by jeffreyhanson** [comment]
Yeah, that's exactly correct - the features in a multi-theme object must all have the same units. I think the rationale behind this was so that we can display percentages and units for the multi-themes when viewed (1) in "group" mode in the advanced version and (2) in the beginner version of the app (which only shows the group mode). E.g., here's the screenshot of the "Biodiversity" multi-theme in the CDFCP app (under advanced mode). Although it just says "units" for the units, this is because the units are specified as "units" (ideally, the data would have something like km^2 as the units or something).

![image](https://user-images.githubusercontent.com/3610005/203144720-3863c7c5-cafb-430c-9304-bdf8ac195672.png)

I agree it would be nice to include features with different units in the same multi-theme - can you think of a way to acheive this and also display the units in the settings widget in a concise/simple way?

**Comment by DanWismer** [comment]
One way that comes to mind is to have the label just display "units" for grouped themes with mixed units along with an icon on hover that says that the grouped theme has mixed units. And maybe listing the different units (km2, km and ha)

**Comment by jeffreyhanson** [comment]
Hmm, so the label would say something like ">= 8% (>= 12 km^2, >= 3 ha)"? IIRC, in an earlier version of the app, we just had percentages, but we got feedback that this was hard for users to understand. So we put in the absolute numbers and units so people could have a better understanding of what the settings mean.

**Comment by DanWismer** [comment]
I was more thinking of an icon with a tool tip that's says `this grouped theme has the following mixed units: km2, km` . And the label will just say `units` 

Would that work?

**Comment by jeffreyhanson** [comment]
Oh - so which number would be displayed in the label? At the moment, it's the minimum - and this sort of makes sense to me because all the values are in the same units so you can directly compare them (e.g. 3000 ha is larger than 2000 ha). If we have different features with different units, then some features might have much smaller values than other ones due to the nature of the units (e.g. ha of habitat vs. km of river) - so just reporting the minimum might be misleading/confusing (e.g. because you might have 5000 ha of forest, 6000 ha of grassland, 9000 ha of desert, and 2 km of river).

**Comment by jeffreyhanson** [comment]
Sorry, this might be a silly question, but would it be possible to report river and shoreline data in km2? E.g., could you (1) apply a buffer to the shoreline to convert from line to polygon, (2) use river width data to create a polygon, and then (3) calculate the amount of river and shoreline km^2 within each planning unit?

**Comment by jeffreyhanson** [comment]
Perhaps these data might work for river widths (https://www.science.org/doi/10.1126/science.aat0636, https://zenodo.org/record/1297434)?

**Comment by DanWismer** [comment]
> Oh - so which number would be displayed in the label? At the moment, it's the minimum - and this sort of makes sense to me because all the values are in the same units so you can directly compare them (e.g. 3000 ha is larger than 2000 ha). If we have different features with different units, then some features might have much smaller values than other ones due to the nature of the units (e.g. ha of habitat vs. km of river) - so just reporting the minimum might be misleading/confusing (e.g. because you might have 5000 ha of forest, 6000 ha of grassland, 9000 ha of desert, and 2 km of river).

ah yes, I was wondering about that. hmmm, I may need to sit on this for a bit.

**Comment by DanWismer** [comment]
> Sorry, this might be a silly question, but would it be possible to report river and shoreline data in km2? E.g., could you (1) apply a buffer to the shoreline to convert from line to polygon, (2) use river width data to create a polygon, and then (3) calculate the amount of river and shoreline km^2 within each planning unit?

What I am currently doing is creating a theme called Lengths and putting river and shoreline in there. I think that approach above would work, however I am not to sure we have width data on our rivers.

**Comment by jeffreyhanson** [comment]
> What I am currently doing is creating a theme called Lengths and putting river and shoreline in there. I think that approach above would work, however I am not to sure we have width data on our rivers.

Ah ok - the dataset I posted above is apparantly global so might have what you're looking for.
