### ISSUE TITLE
renv::restore() on newer versions of R fails to install certain packages 

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#303]
WTW was built on R version `4.1.2 (2021-11-01) -- "Bird Hippie"`

New users have updated versions of R and when they go to clone WTW and `renv::restore()`  a bunch of packages fail to install.

So far the list of failed package installs are: `gert`, `httpuv` ,  `igraph`, `rgdal`, `sf`, `xml2`, `curl`

**Comment by DanWismer** [comment]
trying different things at the moment.

Did a `renv::upgrade()` and got this:
![image](https://user-images.githubusercontent.com/29556279/229155021-125296c6-cfcb-4101-9640-a5aec8c7d86f.png)

**Comment by edwardsmarc** [comment]
RandomFields is no longer supported by CRAN. The current renv lock.file requires v3.3.8. This can be downloaded from the archived [source data](https://cran.r-project.org/src/contrib/Archive/RandomFields/) and works with WTW in R 4.2.2.

In R 4.2.3 RandomFields is not supported and fails to install.

**Comment by DanWismer** [comment]
weird I also got a `pkgload` error
![image](https://user-images.githubusercontent.com/29556279/229227430-26453985-67f3-4fc5-a08d-a349046c8426.png)

**Comment by edwardsmarc** [comment]
pkgload worked for me at v 1.2.1 on R 4.2.2

**Comment by DanWismer** [comment]
I was able to get WTW to install with R 4.2.1, with the following `renv::update` 
- curl , 5.0.0
- exactaxtract, 0.9.1
- gert, 1.9.2
- httpuv, 1.6.9
- igraph, 1.4.1
- rgdal, 1.6-5
- rlang, 1.1.0
- sf, 1.0-12
- usethis, 2.1.6
- testthat, 3.1.7
- xml2, 1.3.3

With all this, I am wondering about  approaches to keep WTW packages up to date and compatible with current versions of R?  I think its unrealistic to maintain multiple versions of WTW. However it would be nice to stay as current as we can.  As we know `renv` creates a time capsule of WTW. @ricschuster, @jeffreyhanson, @edwardsmarc,  when should we start updating the time capsule? 

I did a sanity check and installed WTW on my personal computer using R 4.1.2 and everything worked as designed. 

For fun, I did a renv::update for all packages, and ran WTW and got:  `Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-5.3.1';`

**Comment by edwardsmarc** [comment]
Hey Dan, based on the fact that a minor update to R (e.g. 4.2.2 to 4.2.3) was introducing new breaks in dependencies during our testing last week, I'd say we could develop a protocol for updating the renv.lockfile (e.g. update to latest R version, run renv::restore, update broken dependencies, test WTW, repeat).

I guess the Q is then, how often do we do that update. We could do it every time R is updated, or we could do on a set schedule such as every 6 months.

Some context for @ricschuster and @jeffreyhanson, this came up because I was unable to replicate Dan's renv environment without installing the same version of R that he is using for WTW. Additionally, a couple of the packages in the renv.lock are no longer supported on CRAN, adding some additional steps to get everything set up to run WTW locally. I believe @DanWismer also had some troubles trying to get it running locally for another user last week.

**Comment by edwardsmarc** [comment]
Had to repeat this setup on my new laptop. 

Using R 4.1.2 I couldn't get all packages installed. I was getting an error that `make cannot be found` when running `renv::restore()`. I think might be an issue with RTools. `pkgbuild::rtools_path()` shows that with R 4.1.2, renv uses Rtools 4.0. When using R 4.3 it uses Rtools 4.2 which does not throw the error.

Ended up using R 4.3 with the following package version changes in the lockfile:
- MASS, 7.3-60
- Matrix, 1.5-4.1
- ape, 5.7-1
- class, 7.3-22
- curl, 5.0.1
- exactextractr, 0.9.1
- gert, 1.9.2
- httpuv, 1.6.11
- igraph, 1.4.2
- mgcv, 1.8-42
- nlme, 3.1-162
- pkgdown, 2.0.7 (switched to CRAN repository)
- rgdal, 1.6-7
- rlang, 1.0-13
- sp, 1.6-1
- xml2, 1.3.4

I'll try the R 4.2.1 install again at some point.

**Comment by DanWismer** [comment]
The `make cannot be found` has to do with RStudio / R not knowing where  **rtools40** is.

What I do that works is creating a `.Renviron` file that sits in the documents directory. Double check you have the `.Renviron` file set up properly by confirming in RStudio that their is an icon by the file that looks like this:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/f09822d2-fb33-4d0c-aae6-b5caf9d7d776)

Then add this environmental variable: `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` in the `.Renviron` file. 

Also confirm that you have system environment variable for rtools40:
![image](https://github.com/NCC-CNC/wheretowork/assets/29556279/d0c871d6-40c2-40c8-9991-2537580ba825)

With that, RStudio knows where rtools40 is to install those packages via `renv::restore()`.

**Comment by edwardsmarc** [comment]
Awesome, thanks @DanWismer I'll try this tomorrow.

**Comment by edwardsmarc** [comment]
> The `make cannot be found` has to do with RStudio / R not knowing where **rtools40** is.
> 
> What I do that works is creating a `.Renviron` file that sits in the documents directory. Double check you have the `.Renviron` file set up properly by confirming in RStudio that there is an icon by the file that looks like this: ![image](https://user-images.githubusercontent.com/29556279/245299718-f09822d2-fb33-4d0c-aae6-b5caf9d7d776.png)
> 
> Then add this environmental variable: `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` in the `.Renviron` file.
> 
> Also confirm that you have system environment variable for rtools40: ![image](https://user-images.githubusercontent.com/29556279/245299268-d0c871d6-40c2-40c8-9991-2537580ba825.png)
> 
> With that, RStudio knows where rtools40 is to install those packages via `renv::restore()`.

This worked for me in R4.1.2. I only set the .Renviron PATH and not the system environment (requires admin rights) as described [here](https://cran.r-project.org/bin/windows/Rtools/rtools40.html). I also had to force renv to use the CRAN source instead of mran as detailed [here](https://rstudio.github.io/renv/articles/mran.html) using `options(renv.config.mran.enabled = FALSE)`. Two package versions had to be changed:

- igraph, 1.4.2
- rlang, 1.0.1

**Comment by DanWismer** [comment]
PR #380
