### ISSUE TITLE
Summary outputs don't show area budget and clustering settings

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#312]
'None specified' is reported in runs where an area budget was used.

![image](https://user-images.githubusercontent.com/10728298/234330735-e0f43982-1208-4121-bf80-828d69a4302c.png)

This came up in BC but the bug also exists in the sw-on built in project.

**Comment by edwardsmarc** [comment]
Area budget shows up correct in the sidebar widget. But incorrect in the modal table.

I'm not able to recreate the issue locally. The "Not specified" text doesn't show up when I run `s$render_summary_results()` in `south-west-ontario-no-shiny.R` so I must be missing a step.

**Comment by DanWismer** [comment]
Thanks for catching this Marc! 

The Parameter class I admit is not as explicit as it should be. This is because I added additional fields and scope creep happened. The Parameter class was initially designed to hold only settings that alter the behavior of the optimization (i.e. total area budget and spatial clustering). 

Before lazy loading, the only solution for map performance was to hide layers from the basemap. I decided to put this functionality into the Parameter class. Next, I added the overlap parameter (includes that overlap excludes) and then the file input parameter (uploading previously ran optimization and updating solution settings). I jammed all this stuff in the Parameter class, as at the time it was the easiest for me to accomplish both on the UI and Server side of things. With this all being said, there are fields that are only needed for some of the parameters (ex. units, min_value, max_value etc.) which I agree makes things confusing...

I don't have a strong opinion on how the table looks. I like both options:

**New:**
![image](https://user-images.githubusercontent.com/29556279/236003015-01fb3bee-4d4f-48b0-bcb1-c6a399892164.png)

**Old:**
![image](https://user-images.githubusercontent.com/29556279/236003184-ae2bbf94-9af5-42d3-830b-ad13dcc41cd1.png)

We can go with your version and always change it later need be.

Nice work!

**Comment by edwardsmarc** [comment]
Thanks @DanWismer. The issue was actually raised by some BC staff. There was a second issues they were having around getting different outputs with the same solution settings. Richard thinks this is an issue with the optimality gap. I'm going to look into that and create a separate issue.
