### ISSUE TITLE
Set up dev server and dev branch

### ISSUE THREAD

**Issue by DanWismer** [NCC-CNC/wheretowork#318]
We are now at a spot where we need to do more debugging on the server (example: #316). Carleton has a second server we could try spinning up Sites and make it our dev environment.

**Comment by edwardsmarc** [comment]
We should decide on a good git workflow for dev. Some options:

- Git flow where you have a main and a dev branch
  - Note that the author of this actually [now recommends Git Flow for webapp development](https://nvie.com/posts/a-successful-git-branching-model/)
  - Advantage of this for us is we could have the dev branch continually updated to the dev server so we always have a live dev app.
  - Disadvantage is we need a standardized way to merge dev into main. The author recommends doing a release every time dev is merged to main. This doesn't really fit with our continuous delivery web app which does not need to be versioned.
- [Github Flow](https://docs.github.com/en/get-started/quickstart/github-flow) where all new features are made in branches and merged into main. This is what we currently do with PRs.
  - Advantages are it's simpler, easier to view the commit history, and less work since you don't need to do releases.
  - Disadvantage is for developing we would need to serve different branches to the dev server every time we create a new feature or fix a bug (i.e. it can't just continually watch the dev branch). I'm not sure how we would do this.

**Comment by ricschuster** [comment]
Thanks very much Marc!

As for Git flow and versioning, maybe we should start versioning and create a change log for updates to main. Might be a worthwhile setup and useful to track changes in a straight forward way.

What do you think?

**Comment by DanWismer** [comment]
I have grown to like our current `Github flow`. If we moved to the main-dev branch `git flow` , making changes will take more effort. I am wondering if there is any examples online that show a use case of `Github flow` implemented on both a prod and dev server

**Comment by edwardsmarc** [comment]
I agree our current `Github flow` approach is nice and since there's only two of us actively contributing it's pretty straightforward to make sure `main` is always working.

To @ricschuster's point about versioning, we can do [releases ](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) with whichever workflow we choose. If we stick with `Github flow` we could just do a new release on a timeline (e.g. every 6 months). That's nice because we always have a stable release to fall back on if something really goes wrong on `main`. The only challenge is recording what has changed between releases. We'd likely need to start tagging all issues to a [Milestone ](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) which would be the next release. Then when we do the release we can easily see which issues have been completed since the last release.

**Comment by DanWismer** [comment]
Dev server running Sites is up! https://ncc-dev.carleton.ca 

Next on the list is to work out the dev branch and set things up like I did for the impact app.

**Comment by ricschuster** [comment]
> Dev server running Sites is up! https://ncc-dev.carleton.ca
> 
> Next on the list is to work out the dev branch and set things up like I did for the impact app.

Awesome! 
Great work Dan!

**Comment by DanWismer** [comment]
I haven't read this yet, but a good resource for PR requests:
https://code-review.tidyverse.org/

**Comment by edwardsmarc** [comment]
> I haven't read this yet, but a good resource for PR requests: https://code-review.tidyverse.org/

This looks very helpful! Thanks @DanWismer

**Comment by edwardsmarc** [comment]
> I haven't read this yet, but a good resource for PR requests: https://code-review.tidyverse.org/

I read through this @DanWismer. Lots of good tips and best practices. I think with this, and a well thought out git workflow (i.e. how/when to merge dev into main) we should be on the right track.

**Comment by DanWismer** [comment]
dev server is running, I will close this. We can revisit how we will do a dev branch (if needed)
