### ISSUE TITLE
new_dataset_from_auto() fails

### ISSUE THREAD

**Issue by edwardsmarc** [NCC-CNC/wheretowork#384]
I'm getting the following message when calling new_dataset_from_auto() following PR #380:

`Error in stop(assertError(attr(res, "msg"))) : bad error message`

I get this when trying to prep my own WTW data, and also when I run the example from `?new_dataset_from_auto`

**Comment by DanWismer** [comment]
Can you confirm you are using this version  `0.2.1` of `assertthat`?

**Comment by edwardsmarc** [comment]
The issue here was that I was using the old data prep scripts that are still formatted for `raster` and not `terra`. Once I switched to terra the function worked so you can close this issue.

**Comment by jeffreyhanson** [comment]
Just in case this you see this error message again, it's caused by incorrect error handling with the `assertthat::assert_that()`. Basically, the code has detected an issue with some input arguments for a function, but it's unable to display a useful error message. To help track down what's going wrong, I suggest using `traceback()`. This will exactly where the error is happening in the call stack.

**Comment by DanWismer** [comment]
Thanks @edwardsmarc ! I will create a release for our wtw-data-prep so we have a working version for WTW 0.0.9000. And then an updated version that works with WTW 1.0.0.
